[[ArrayInterface]]
deps = ["Requires", "Test"]
git-tree-sha1 = "6a1a371393e56f5e8d5657fe4da4b11aea0bfbae"
uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
version = "0.1.1"

[[BandedMatrices]]
deps = ["FillArrays", "LazyArrays", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "ac5b244e729922c61f75c2e4478e13e8949b1f56"
uuid = "aae01518-5342-5314-be14-df237901396f"
version = "0.8.2"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "055eb2690182ebc31087859c3dd8598371d3ef9e"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.3"

[[BoundaryValueDiffEq]]
deps = ["BandedMatrices", "DiffEqBase", "DiffEqDiffTools", "ForwardDiff", "LinearAlgebra", "NLsolve", "Reexport", "SparseArrays", "Test"]
git-tree-sha1 = "0f4a4f86ae63671efd9b41de9dea8ad993f2daad"
uuid = "764a87c0-6b3e-53db-9096-fe964310641d"
version = "2.2.3"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "f60954495a7afcee4136f78d1d60350abd37a409"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.1"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "195a3ffcb8b0762684b6821de18f83a16455c6ea"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.0.0"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections", "Random", "Serialization", "Test"]
git-tree-sha1 = "ca971f03e146cf144a9e2f2ce59674f5bf0e8038"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.15.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelayDiffEq]]
deps = ["DataStructures", "DiffEqBase", "DiffEqDiffTools", "ForwardDiff", "MuladdMacro", "NLSolversBase", "OrdinaryDiffEq", "RecursiveArrayTools", "Reexport", "Roots", "Test"]
git-tree-sha1 = "8573109883782a75c0d8574150a1beddc420ff66"
uuid = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
version = "5.2.0"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffBase]]
deps = ["StaticArrays"]
git-tree-sha1 = "38522d70e417cf9ace93848f17eb9fff20d486d2"
uuid = "c5cfe0b6-c10a-51a5-87e3-fd79235949f0"
version = "0.3.2"

[[DiffEqBase]]
deps = ["Compat", "IteratorInterfaceExtensions", "LinearAlgebra", "RecipesBase", "RecursiveArrayTools", "Requires", "Roots", "SparseArrays", "StaticArrays", "Statistics", "SuiteSparse", "TableTraits", "Test", "TreeViews"]
git-tree-sha1 = "69e00a95b2686c182a3a733e375a3c28c307be65"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
version = "5.5.1"

[[DiffEqCallbacks]]
deps = ["DataStructures", "DiffEqBase", "LinearAlgebra", "OrdinaryDiffEq", "RecipesBase", "RecursiveArrayTools", "StaticArrays", "Test"]
git-tree-sha1 = "027a13f010f2a93b2df725b7f6202590ce6f559d"
uuid = "459566f4-90b8-5000-8ac3-15dfb0a30def"
version = "2.5.2"

[[DiffEqDiffTools]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "30f82c63cb9d293513b360572e283c19577fcf82"
uuid = "01453d9d-ee7c-5054-8395-0335cb756afa"
version = "0.8.1"

[[DiffEqFinancial]]
deps = ["DiffEqBase", "DiffEqNoiseProcess", "LinearAlgebra", "Markdown", "RandomNumbers", "Test"]
git-tree-sha1 = "f250512b982b771f6bdb3df05b89df314f2c2580"
uuid = "5a0ffddc-d203-54b0-88ba-2c03c0fc2e67"
version = "2.1.0"

[[DiffEqJump]]
deps = ["Compat", "DataStructures", "DiffEqBase", "FunctionWrappers", "LinearAlgebra", "Parameters", "PoissonRandom", "Random", "RandomNumbers", "RecursiveArrayTools", "Statistics", "Test", "TreeViews"]
git-tree-sha1 = "784b979eeca8e9586aea9e63edbdcf5573bf9449"
uuid = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
version = "6.1.1"

[[DiffEqMonteCarlo]]
deps = ["DiffEqBase", "Distributed", "Random", "RecursiveArrayTools", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "abaf6fa95b05c5c49fd1fb57a901caed10aacd0e"
uuid = "78ddff82-25fc-5f2b-89aa-309469cbf16f"
version = "0.14.0"

[[DiffEqNoiseProcess]]
deps = ["DataStructures", "DiffEqBase", "LinearAlgebra", "Random", "RandomNumbers", "RecipesBase", "RecursiveArrayTools", "ResettableStacks", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "328e3c1629059a7ad150801310cba831557c7e2e"
uuid = "77a26b50-5914-5dd7-bc55-306e6241c503"
version = "3.1.0"

[[DiffEqOperators]]
deps = ["DiffEqBase", "LinearAlgebra", "Random", "SparseArrays", "StaticArrays", "Test"]
git-tree-sha1 = "332eea616ae687e7e4581602947ad5f053c7c650"
uuid = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
version = "3.4.0"

[[DiffEqPhysics]]
deps = ["Dates", "DiffEqBase", "DiffEqCallbacks", "ForwardDiff", "LinearAlgebra", "Printf", "Random", "RecipesBase", "RecursiveArrayTools", "Reexport", "StaticArrays", "Test"]
git-tree-sha1 = "d3dbc53318a6477f496ae2347db98c3ded36c486"
uuid = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
version = "3.1.0"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "34a4a1e8be7bc99bc9c611b895b5baf37a80584c"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.4"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "dc0869fb2f5b23466b32ea799bd82c76480167f7"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.10"

[[DifferentialEquations]]
deps = ["BoundaryValueDiffEq", "DelayDiffEq", "DiffEqBase", "DiffEqCallbacks", "DiffEqFinancial", "DiffEqJump", "DiffEqMonteCarlo", "DiffEqNoiseProcess", "DiffEqPhysics", "DimensionalPlotRecipes", "LinearAlgebra", "MultiScaleArrays", "OrdinaryDiffEq", "Random", "RecursiveArrayTools", "Reexport", "SteadyStateDiffEq", "StochasticDiffEq", "Sundials", "Test"]
git-tree-sha1 = "cabb3b0cd80afcb703e61fcf28f54505d9ae10a1"
uuid = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
version = "6.3.0"

[[DimensionalPlotRecipes]]
deps = ["LinearAlgebra", "RecipesBase", "Test"]
git-tree-sha1 = "d348688f9a3d02c24455327231c450c272b7401c"
uuid = "c619ae07-58cd-5f6d-b883-8f17bd6a98f9"
version = "0.2.0"

[[Distances]]
deps = ["LinearAlgebra", "Printf", "Random", "Statistics", "Test"]
git-tree-sha1 = "a135c7c062023051953141da8437ed74f89d767a"
uuid = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
version = "0.8.0"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[ExponentialUtilities]]
deps = ["LinearAlgebra", "Printf", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "6fad21cd7637d0ad6a7661f8abea1149922d6c9c"
uuid = "d4d017d3-3776-5f7e-afef-a10c40355c18"
version = "1.4.0"

[[FillArrays]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "2def0123a4f3572234405b0e3d80bfe5d3e1a2a4"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "0.5.0"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "4c4d727f1b7e0092134fabfab6396b8945c1ea5b"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.10.3"

[[FunctionWrappers]]
deps = ["Compat"]
git-tree-sha1 = "49bf793ebd37db5adaa7ac1eae96c2c97ec86db5"
uuid = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
version = "1.0.0"

[[GenericSVD]]
deps = ["LinearAlgebra", "Random", "Test"]
git-tree-sha1 = "8aa93c3f3d81562a8962047eafcc5712af0a0f59"
uuid = "01680d73-4ee2-5a08-a1aa-533608c188bb"
version = "0.2.1"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IteratorInterfaceExtensions]]
deps = ["Test"]
git-tree-sha1 = "5484e5ede2a4137b9643f4d646e8e7b87b794415"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "0.1.1"

[[LazyArrays]]
deps = ["FillArrays", "LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "5e65ca3ab05ae82e441fa51e9e91fb3fca1e7bb5"
uuid = "5078a376-72f3-5289-bfd5-ec5146d43c02"
version = "0.7.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LineSearches]]
deps = ["LinearAlgebra", "NLSolversBase", "NaNMath", "Parameters", "Printf", "Test"]
git-tree-sha1 = "54eb90e8dbe745d617c78dee1d6ae95c7f6f5779"
uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
version = "7.0.1"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "3fd1a3022952128935b449c33552eb65895380c1"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.5"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[MuladdMacro]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "41e6e7c4b448afeaddaac7f496b414854f83b848"
uuid = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
version = "0.2.1"

[[MultiScaleArrays]]
deps = ["DiffEqBase", "LinearAlgebra", "RecursiveArrayTools", "Statistics", "StochasticDiffEq", "Test", "TreeViews"]
git-tree-sha1 = "4220ceea71186db2bb45cb817984c99e563f3662"
uuid = "f9640e96-87f6-5992-9c3b-0743c6a49ffa"
version = "1.4.0"

[[NLSolversBase]]
deps = ["Calculus", "DiffEqDiffTools", "DiffResults", "Distributed", "ForwardDiff", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "0c6f0e7f2178f78239cfb75310359eed10f2cacb"
uuid = "d41bc354-129a-5804-8e4c-c37616107c6c"
version = "7.3.1"

[[NLsolve]]
deps = ["DiffBase", "DiffEqDiffTools", "Distances", "ForwardDiff", "LineSearches", "LinearAlgebra", "NLSolversBase", "Printf", "Reexport", "SparseArrays", "Test"]
git-tree-sha1 = "0e046f4f72801c9782d64db972ce66a85d3473f1"
uuid = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
version = "3.0.1"

[[NaNMath]]
deps = ["Compat"]
git-tree-sha1 = "ce3b85e484a5d4c71dd5316215069311135fa9f2"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.2"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "85619a3f3e17bb4761fe1b1fd47f0e979f964d5b"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.0.2"

[[OrdinaryDiffEq]]
deps = ["DataStructures", "DiffEqBase", "DiffEqDiffTools", "DiffEqOperators", "ExponentialUtilities", "ForwardDiff", "GenericSVD", "InteractiveUtils", "LinearAlgebra", "Logging", "MuladdMacro", "NLsolve", "Parameters", "Printf", "Random", "RecursiveArrayTools", "Reexport", "SparseArrays", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "4de64a8a4acd30c2ca58a5dbf682546f60fff498"
uuid = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
version = "5.4.0"

[[Parameters]]
deps = ["Markdown", "OrderedCollections", "REPL", "Test"]
git-tree-sha1 = "70bdbfb2bceabb15345c0b54be4544813b3444e4"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.10.3"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PoissonRandom]]
deps = ["Random", "Statistics", "Test"]
git-tree-sha1 = "44d018211a56626288b5d3f8c6497d28c26dc850"
uuid = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
version = "0.4.0"

[[Polynomials]]
deps = ["LinearAlgebra", "SparseArrays", "Test"]
git-tree-sha1 = "62142bd65d3f8aeb2226ec64dd8493349147df94"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "0.5.2"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RandomNumbers]]
deps = ["Pkg", "Printf", "Random", "Requires", "Test"]
git-tree-sha1 = "2b965faf50a587c8b419b883e8f19c3bfedde76d"
uuid = "e6cf234a-135c-5ec9-84dd-332b85af5143"
version = "1.2.0"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "0b3cb370ee4dc00f47f1193101600949f3dcf884"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.6.0"

[[RecursiveArrayTools]]
deps = ["ArrayInterface", "RecipesBase", "Requires", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "187ea7dd541955102c7035a6668613bdf52022ca"
uuid = "731186ca-8d62-57ce-b412-fbd966d074cd"
version = "0.20.0"

[[Reexport]]
deps = ["Pkg"]
git-tree-sha1 = "7b1d07f411bc8ddb7977ec7f377b97b158514fe0"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[ResettableStacks]]
deps = ["Random", "StaticArrays", "Test"]
git-tree-sha1 = "8b4f6cf3c97530e1ba7177ad3bc2b134373da851"
uuid = "ae5879a3-cd67-5da8-be7f-38c6eb64a37b"
version = "0.6.0"

[[Roots]]
deps = ["Compat", "Printf"]
git-tree-sha1 = "2e7171b6f3b58b81201ba37d9e1220aff6d904a1"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
version = "0.7.4"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Libdl", "Test"]
git-tree-sha1 = "0b45dc2e45ed77f445617b99ff2adf0f5b0f23ea"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.2"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "3841b39ed5f047db1162627bf5f80a9cd3e39ae2"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.10.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[SteadyStateDiffEq]]
deps = ["Compat", "DiffEqBase", "DiffEqCallbacks", "LinearAlgebra", "NLsolve", "Reexport", "Test"]
git-tree-sha1 = "fe9852d18c3e30f384003da50d6049e5fbc97071"
uuid = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
version = "1.4.0"

[[StochasticDiffEq]]
deps = ["DataStructures", "DiffEqBase", "DiffEqDiffTools", "DiffEqNoiseProcess", "DiffEqOperators", "Distributed", "ForwardDiff", "LinearAlgebra", "Logging", "MuladdMacro", "NLsolve", "Parameters", "Random", "RandomNumbers", "RecursiveArrayTools", "Reexport", "SparseArrays", "StaticArrays", "Test"]
git-tree-sha1 = "af003918bf0ccc7a712b1c8b4d40df59bc76ca8d"
uuid = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
version = "6.1.1"

[[SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Sundials]]
deps = ["BinaryProvider", "DataStructures", "DiffEqBase", "Libdl", "LinearAlgebra", "Reexport", "SparseArrays", "Test"]
git-tree-sha1 = "b3dc62f5b06f621816ab30ef3db5dbf0d3fdd364"
uuid = "c3572dad-4567-51f8-b174-8c6c989267f4"
version = "3.3.0"

[[TableTraits]]
deps = ["IteratorInterfaceExtensions", "Test"]
git-tree-sha1 = "eba4b1d0a82bdd773307d652c6e5f8c82104c676"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "0.4.1"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TreeViews]]
deps = ["Test"]
git-tree-sha1 = "8d0d7a3fe2f30d6a7f833a5f19f7c7a5b396eae6"
uuid = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
version = "0.3.0"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
